### ISSUE TITLE
Create Operating Systems course

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#75]
Simplified Coding has courses on Web Development, Programming Fundamentals, and Robotics. We should also invest in courses for Windows and Linux. How to use each OS and some tips and tricks to get the most out of each system. The Windows course will be focused on people who wish to learn how to use their computer and some tricks to boost their productivity, while Linux will be focused on long-time Windows and Mac users, who have some good knowledge of their computer and want to try something more challenging. We will be avoiding creating a Mac OS course, as our team does not own any Mac systems and think that Mac OS isn't suitable.

[TODO] Split into lessons | Roadmap
```[tasklist]
### Tasks
```

**Comment by GalaxyGamingBoy** [comment]
@odysseuskir  Can you expand on what the linux and windows course will teach

**Comment by GalaxyGamingBoy** [comment]
If you add the terminal, it might be better for the simple command to be labeled as UNIX as they are **_similar_** in both Linux and Mac

**Comment by Nikos1508** [comment]
THIS MUST BE DESTROYED

**Comment by Nikos1508** [comment]
We have nothing to write about. We thought about making a terminal course but we can put it in the basic programming courses.

**Comment by odysseuskir** [comment]
The terminal is **not** basic programming. You should know Nikos because you barely know anything in Windows.
