### ISSUE TITLE
Basic Programming Terms course

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#76]
Most users who are starting in programming probably don't know terms like `Code editor`, `IDE`, or file extension for Python files. That's why we could create a course to introduce users to these terms. It would be an introductory course that users should follow before any other.

Notes:
1. Thanks to @Devnol for bringing this issue to my attention
2. This is still a topic for discussion and may change
```[tasklist]
### Tasks
```

**Comment by GalaxyGamingBoy** [comment]
https://simplifiedcoding.notion.site/Basic-Programming-Terms-b995d39bdb4845e9a2130c5828ce2818?pvs=4
