### ISSUE TITLE
Basic Computer Concepts course

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#81]
This course will help users to understand basic Computer Concepts that many of us take for granted. Concepts like, file systems, browsers, the internet, and more. This course will be very useful to people who know how to operate a computer, but aren't familiar with concepts and terms that are essential to learning Computer Programming

**Comment by GalaxyGamingBoy** [comment]
https://simplifiedcoding.notion.site/Basic-Computer-Concepts-8fae491223f24f498c0361f5aea40288?pvs=4
