### ISSUE TITLE
Move donations to footer

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#84]
The Simplified Coding Team has agreed that the donations are invasive in their position on the homepage. That is why we will be moving it to the footer with a discrete icon asking for donations. That button will redirect to Hack Club Bank's donation page.
```[tasklist]
### Tasks
- [ ] Remove element
- [ ] Add to footer donate icon
- [ ] Add link
```

**Comment by Nikos1508** [comment]
I have finished that but the icon cannot load.

**Comment by odysseuskir** [comment]
If the icon can't load, then there's a bug and this isn't finished.
