### ISSUE TITLE
Lessons for usage of online and local code editors

### ISSUE THREAD

**Issue by Nikos1508** [simplified-coding/simplified-coding.github.io#85]
```[tasklist]
### Tasks
- [ ] Online
- [ ] Local
```

**Comment by Nikos1508** [comment]
This should be created before the advanced lessons of C++

**Comment by GalaxyGamingBoy** [comment]
https://simplifiedcoding.notion.site/Online-and-Local-Code-Editors-c860caf3fb3f47449f4b7e53d26c4008?pvs=25
